### ISSUE TITLE
Issue downloading

### ISSUE THREAD

**Issue by AutoJames** [twitter-archive/twemperf#1]
I get a 403 error when trying to download on my server.

Here is the output:
# curl -vv -o /dev/null -D- https://twemperf.googlecode.com/files/mcperf-0.1.1.tar.gz
- About to connect() to twemperf.googlecode.com port 443 (#0)
-   Trying 74.125.21.82... connected
- Connected to twemperf.googlecode.com (74.125.21.82) port 443 (#0)
- Initializing NSS with certpath: sql:/etc/pki/nssdb
-   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
- SSL connection using SSL_RSA_WITH_RC4_128_SHA
- Server certificate:
-       subject: CN=*.googlecode.com,O=Google Inc,L=Mountain View,ST=California,C=US
-       start date: Feb 12 15:06:32 2014 GMT
-       expire date: Jun 12 00:00:00 2014 GMT
-       common name: *.googlecode.com
-       issuer: CN=Google Internet Authority G2,O=Google Inc,C=US
  > GET /files/mcperf-0.1.1.tar.gz HTTP/1.1
  > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
  > Host: twemperf.googlecode.com
  > Accept: _/_
  >
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 403 Forbidden
  HTTP/1.1 403 Forbidden
  < Content-Length: 1428
  Content-Length: 1428
  < Content-Type: text/html; charset=UTF-8
  Content-Type: text/html; charset=UTF-8
  < Date: Sat, 22 Feb 2014 20:22:50 GMT
  Date: Sat, 22 Feb 2014 20:22:50 GMT
  < Server: GFE/2.0
  Server: GFE/2.0
  < Alternate-Protocol: 443:quic
  Alternate-Protocol: 443:quic

**Comment by manjuraj** [comment]
curl -O https://twemperf.googlecode.com/files/mcperf-0.1.1.tar.gz works just fine
